version: '3.7'

services: 
    db:
        container_name: pg-con
        build: ./db
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: db
        ports: 
            - ${DB_PORT}:5432
        
    api:
        container_name: node-con
        build: ./api
        volumes:
            - ./api:/app/
        environment:
          PORT: ${API_PORT}
          DB_PORT: ${DB_PORT}
        depends_on:
            - db
        ports:
            - ${API_PORT}:${API_PORT}
        links:
            - db

    web:
        image: php:8.0-apache
        container_name: php-con
        working_dir: /var/www/html
        stdin_open: true
        tty: true
        volumes: 
            - ./website:/var/www/html
        ports: 
            - "8888:80"
        links:
            - api