version: '3.7'

services: 
    db:
        image: postgres:14
        container_name: pg-con
        environment:
            POSTGRES_USER: pg_user
            POSTGRES_PASSWORD: pg_password
            POSTGRES_DB: pg_db
        volumes:
            - ./DB/init.sql:/docker-entrypoint-initdb.d/init.sql
        ports: 
            - 5432:5432
        
    api:
        build: './API'
        container_name: node-con
        depends_on:
            - db
        volumes:
            - ./API:/home/node/API
        ports:
            - "2684:2684"
        links:
            - db

    web:
        image: php:8.0-apache
        container_name: php-con
        working_dir: /var/www/html
        stdin_open: true
        tty: true
        volumes: 
            - ./Website:/var/www/html
        ports: 
            - "8888:80"
        links:
            - api